version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tachLocalPass1
      - POSTGRES_DB=tachLocal
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  minio:
    image: minio/minio:RELEASE.2022-02-16T00-35-27Z
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      - MINIO_ACCESS_KEY=tachignite
      - MINIO_SECRET_KEY=dNvRMDEgbHQKSVQDnz
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/nginx/certs/
    depends_on:
      - app
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  minio:
  redis:
    driver: local
