/* eslint-disable no-unused-vars */

export enum ApiKeysEnum {
  GetCartItems = 'getCartItems',
  RemoveAllItemsFromCart = 'RemoveAllItemsFromCart',
  GetAllProducts = 'getAllProducts',
  GetAllFavoriteProducts = 'getAllFavoriteProducts',
  GetAllServices = 'getAllServices',
  GetProduct = 'getProduct',
  GetService = 'getService',
  GetAllUsers = 'getAllUsers',
  GetUser = 'getUser',
  GetProfileUser = 'getProfileUser',
  GetCustomerUserProfile = 'GetCustomerUserProfile',
  GetRoles = 'getRoles',
  TotalUsersCount = 'totalUsersCount',
  GetCategory = 'getCategory',
  GetAllCategories = 'getAllCategories',
  GetAllInquiries = 'getAllInquiries',
  GetSingleInquiry = 'getSingleInquiry',
  GetAdminProfile = 'getAdminProfile',
  GetAllAdminNotifications = 'getAllAdminNotifications',
  GetAllUnreadNotificationCount = 'getAllUnreadNotificationCount',
  CreateOrders = 'createOrders',
  GetAllOrders = 'GetAllOrders',
  GetSingleOrders = 'GetSingleOrders',
  GetAnnouncement = 'GetAnnouncement',
  GetAnnouncementArticles = 'GetAnnouncementArticles',
  GetAnnouncementTimeline = 'GetAnnouncementTimeline',
  GetAllFriendlyIdProducts = 'GetAllFriendlyIdProducts',
  GetAnnouncementSingleArticle = 'GetAnnouncementSingleArticle',
  GetAdminDashboardOverview = 'GetAdminDashboardOverview',
  GetServices = 'GetServices',
  GetUniqueService = 'GetUniqueService',
  GetServiceSlots = '/services/slots',
  GetAllBookings = 'GetAllBookings',
  GetSingleBooking = 'GetSingleBooking',
}
